const VERSION="v56";
const CORE_CACHE=`gym-tracker-core-${VERSION}`;
const RUNTIME_CACHE=`gym-tracker-runtime-${VERSION}`;
const INDEX_URL=new URL("./index.html",self.registration.scope).href;
const CORE_ASSETS=["./","./index.html","./manifest.webmanifest","./icon-180.png","./icon-192.png","./icon-512.png"];
self.addEventListener("install",event=>{event.waitUntil((async()=>{const cache=await caches.open(CORE_CACHE);await Promise.allSettled(CORE_ASSETS.map(async asset=>{const response=await fetch(asset,{cache:"reload"});if(response.ok)await cache.put(asset,response)}));await self.skipWaiting()})())});
self.addEventListener("activate",event=>{event.waitUntil((async()=>{const keep=new Set([CORE_CACHE,RUNTIME_CACHE]),keys=await caches.keys();await Promise.all(keys.filter(key=>!keep.has(key)).map(key=>caches.delete(key)));await self.clients.claim()})())});
async function navigationNetworkFirst(request){const cache=await caches.open(CORE_CACHE);try{const response=await fetch(request,{cache:"no-store"});if(response.ok)await cache.put(INDEX_URL,response.clone());return response}catch(_){return (await cache.match(INDEX_URL))||(await cache.match("./"))}}
async function imageCacheFirst(request){const cache=await caches.open(RUNTIME_CACHE),cached=await cache.match(request,{ignoreSearch:true});const network=fetch(request).then(async response=>{if(response.ok)await cache.put(request,response.clone());return response});if(cached){network.catch(()=>{});return cached}return network}
async function assetCacheFirst(request){const cache=await caches.open(RUNTIME_CACHE),cached=await cache.match(request,{ignoreSearch:true});if(cached)return cached;const response=await fetch(request);if(response.ok)await cache.put(request,response.clone());return response}
self.addEventListener("fetch",event=>{const request=event.request;if(request.method!=="GET")return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(request.mode==="navigate"){event.respondWith(navigationNetworkFirst(request));return}if(request.destination==="image"||url.pathname.includes("/assets/exercises/")){event.respondWith(imageCacheFirst(request).catch(()=>caches.match(request,{ignoreSearch:true})));return}event.respondWith(assetCacheFirst(request).catch(()=>caches.match("./index.html")))});
self.addEventListener("message",event=>{const data=event.data||{};if(data.type==="SKIP_WAITING")self.skipWaiting();if(data.type==="PURGE_URL"&&data.url)event.waitUntil((async()=>{const cache=await caches.open(RUNTIME_CACHE);await cache.delete(data.url,{ignoreSearch:true})})())});
