/* Gym Tracker v129 core: stable Settings, date-aware Calendar, Today visibility */
(()=>{
'use strict';
const G=window.GymV129=window.GymV129||{};
G.release='v129';G.PLAN_KEY='gymPlannedWorkoutsV126';
G.q=(s,r=document)=>r?.querySelector?.(s)||null;G.qa=(s,r=document)=>Array.from(r?.querySelectorAll?.(s)||[]);
G.safe=v=>typeof esc==='function'?esc(String(v??'')):String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
G.cs=()=>{try{return typeof lang==='function'&&lang()==='cs'}catch(_){return true}};
G.today=()=>{try{return typeof today==='function'?today():new Date().toISOString().slice(0,10)}catch(_){return new Date().toISOString().slice(0,10)}};
G.readPlans=()=>{try{return JSON.parse(localStorage.getItem(G.PLAN_KEY)||'{}')||{}}catch(_){return {}}};
G.writePlans=v=>{try{localStorage.setItem(G.PLAN_KEY,JSON.stringify(v||{}))}catch(_){}};
G.toast=msg=>{try{if(typeof showToast==='function')showToast(msg)}catch(_){}};
G.setDate=iso=>{try{selectedWorkoutDate=iso}catch(_){}try{calendarViewDate=iso}catch(_){}try{localStorage.setItem('gymSelectedWorkoutDate',iso)}catch(_){}};

function installSettings(){
 try{setLanguage=function(value){if(!['cs','en'].includes(value)||state.settings.language===value)return;state.settings.language=value;saveState();applyLanguage()};window.setLanguage=setLanguage}catch(e){console.warn('[v129 language]',e)}
 try{setTheme=function(value){const next=value==='dark'?'dark':'light';if(state.settings.theme===next)return;state.settings.theme=next;saveState();applyTheme();if(typeof renderMore==='function')renderMore()};window.setTheme=setTheme}catch(e){console.warn('[v129 theme]',e)}
}
function installPlanHooks(){
 try{const native=typeof trainingDayForIso==='function'?trainingDayForIso:null;if(native&&!native.__v129){const f=function(iso){return G.readPlans()[iso]||native.call(this,iso)};f.__v129=true;trainingDayForIso=f;window.trainingDayForIso=f}}catch(e){console.warn('[v129 training day]',e)}
 try{const native=typeof isPlannedStrengthDate==='function'?isPlannedStrengthDate:null;if(native&&!native.__v129){const f=function(iso){return !!G.readPlans()[iso]||native.call(this,iso)};f.__v129=true;isPlannedStrengthDate=f;window.isPlannedStrengthDate=f}}catch(e){console.warn('[v129 planned date]',e)}
}
const originalCalendar=(()=>{try{return typeof v124OpenCalendarDay==='function'?v124OpenCalendarDay:null}catch(_){return null}})();
const dateRenderer=(()=>{try{if(typeof showTodayV122==='function')return showTodayV122}catch(_){}try{return typeof showToday==='function'?showToday:null}catch(_){return null}})();
function sessionLabel(day){try{const p=BASE_PLANS?.[day];return p?.['title_'+(G.cs()?'cs':'en')]||p?.title_en||day}catch(_){return day}}
function resolveDay(iso,preferred=''){const planned=G.readPlans()[iso];if(planned)return planned;if(preferred)return preferred;try{const d=typeof trainingDayForIso==='function'?trainingDayForIso(iso):'';if(d)return d}catch(_){}try{if(typeof currentProgramDay==='function')return currentProgramDay()}catch(_){}try{if(typeof recommendedDay==='function')return recommendedDay()}catch(_){}return 'monday'}
function rootFor(day){return document.getElementById(day)||document.querySelector('.screen.active')||document.getElementById('today')}
G.resolveDay=resolveDay;G.rootFor=rootFor;
function showDate(day,iso){const date=String(iso||G.today()),target=resolveDay(date,day);G.setDate(date);try{selectedTodayDay=target}catch(_){}const result=dateRenderer?dateRenderer(target,date):undefined;decorate(target,date);return result}
try{showToday=function(day,date){const iso=String(date||(()=>{try{return selectedWorkoutDate}catch(_){return ''}})()||G.today());const target=resolveDay(iso,day);if(iso===G.today()){try{if(state.activeWorkout?.day)return showDate(state.activeWorkout.day,iso)}catch(_){}}return showDate(target,iso)};window.showToday=showToday}catch(e){console.warn('[v129 show today]',e)}
function plannerHtml(iso){const chosen=G.readPlans()[iso]||'',days=['monday','wednesday','friday'];return `<section class="v129-planner" data-v129-date="${G.safe(iso)}"><div class="v129-planner-head"><div><small>${G.cs()?'PLÁNOVÁNÍ':'PLANNING'}</small><h3>${chosen?(G.cs()?'Naplánovaný trénink':'Planned workout'):(G.cs()?'Naplánovat trénink':'Plan workout')}</h3></div><span>▦</span></div><p>${G.cs()?'Vyber session pro tento den. Uloží se k datu a zůstane i po zavření aplikace.':'Choose a session for this date. It stays saved after closing the app.'}</p><div class="v129-plan-grid">${days.map((d,i)=>`<button type="button" data-v129-day="${d}" class="${chosen===d?'selected':''}"><b>${G.safe(sessionLabel(d))}</b><small>Session ${i+1}</small></button>`).join('')}</div>${chosen?`<button type="button" class="v129-clear-plan">${G.cs()?'Zrušit plán pro tento den':'Remove plan for this day'}</button>`:''}</section>`}
function bindPlanner(root,iso){if(!root||root.dataset.bound==='1')return;root.dataset.bound='1';G.qa('[data-v129-day]',root).forEach(b=>b.addEventListener('click',()=>{const plans=G.readPlans();plans[iso]=b.dataset.v129Day;G.writePlans(plans);showDate(b.dataset.v129Day,iso);G.toast(G.cs()?'Trénink naplánován ✓':'Workout planned ✓')}));G.q('.v129-clear-plan',root)?.addEventListener('click',()=>{const plans=G.readPlans();delete plans[iso];G.writePlans(plans);showDate(resolveDay(iso,''),iso);G.toast(G.cs()?'Plán zrušen':'Plan removed')})}
function renderPlanner(day,iso){const root=rootFor(day);if(!root)return;G.qa('.v129-planner,.v128-future-planner,.v126-future-planner').forEach(x=>x.remove());if(iso<=G.today())return;const anchor=G.q('.v120-calendar',root)||G.q('.calendar-drag-viewport',root)||G.q('.modern-week-strip',root)?.parentElement||G.q('.modern-today-head',root);if(!anchor)return;anchor.insertAdjacentHTML('afterend',plannerHtml(iso));bindPlanner(G.q('.v129-planner',root),iso)}
function installCalendar(){try{const route=function(iso){const date=String(iso||'');if(!date)return;const now=G.today();if(date<now){if(originalCalendar)return originalCalendar.call(this,date);return}if(date===now){G.setDate(now);return showDate(resolveDay(now,''),now)}return showDate(resolveDay(date,''),date)};route.__v129=true;v124OpenCalendarDay=route;window.v124OpenCalendarDay=route}catch(e){console.warn('[v129 calendar]',e)}}
let completedHidden=false;G.getCompletedHidden=()=>completedHidden;
function listFor(root){return G.q('.today-preview-list,.plan-preview-list',root)}
function applyCompleted(day){const root=rootFor(day),list=listFor(root);if(!root||!list)return;const cards=G.qa(':scope > .modern-exercise-card,:scope > details[data-instance-id]',list),done=cards.filter(c=>c.classList.contains('exercise-done'));done.forEach(c=>c.classList.toggle('v129-completed-hidden',completedHidden));let tools=G.q('.v129-completed-tools',root);if(!done.length){tools?.remove();return}if(!tools){tools=document.createElement('div');tools.className='v129-completed-tools';const b=document.createElement('button');b.type='button';b.addEventListener('click',()=>{completedHidden=!completedHidden;applyCompleted(day)});tools.appendChild(b);(G.q('.v120-exercise-heading',root)||list).insertAdjacentElement('afterend',tools)}const b=G.q('button',tools);if(b)b.textContent=completedHidden?(G.cs()?'Ukázat hotové':'Show completed'):(G.cs()?'Skrýt hotové':'Hide completed')}
G.applyCompleted=applyCompleted;
function moveMeasurement(day){const root=rootFor(day);if(!root)return;const card=G.q('.monday-measurement-card.measurement-saved',root);if(!card)return;card.removeAttribute('open');card.classList.add('v129-measurement-bottom');if(root.lastElementChild!==card)root.appendChild(card)}
function decorate(day,iso){requestAnimationFrame(()=>{const root=rootFor(day);if(!root)return;root.classList.add('v129-today');applyCompleted(day);moveMeasurement(day);renderPlanner(day,iso);G.qa('.modern-exercise-card',root).forEach(c=>{c.classList.toggle('v129-state-done',c.classList.contains('exercise-done'));c.classList.toggle('v129-state-progress',c.classList.contains('exercise-in-progress'));c.classList.toggle('v129-state-skipped',c.classList.contains('exercise-skipped'))})})}
G.decorate=decorate;
function installRenderHooks(){
 try{const native=typeof renderDay==='function'?renderDay:null;if(native&&!native.__v129){const f=function(day,...args){const r=native.call(this,day,...args);let iso=G.today();try{iso=selectedWorkoutDate||iso}catch(_){}decorate(day,iso);return r};f.__v129=true;renderDay=f;window.renderDay=f}}catch(e){console.warn('[v129 render day]',e)}
 try{const native=typeof refreshTodayPreviewStatus==='function'?refreshTodayPreviewStatus:null;if(native&&!native.__v129){const f=function(day,id,...args){const r=native.call(this,day,id,...args);applyCompleted(day);return r};f.__v129=true;refreshTodayPreviewStatus=f;window.refreshTodayPreviewStatus=f}}catch(e){console.warn('[v129 status]',e)}
 try{const native=typeof renderMore==='function'?renderMore:null;if(native&&!native.__v129){const f=function(...args){const r=native.apply(this,args);G.q('#more')?.classList.add('v129-settings');return r};f.__v129=true;renderMore=f;window.renderMore=f}}catch(e){console.warn('[v129 settings render]',e)}
 try{const native=typeof renderLive==='function'?renderLive:null;if(native&&!native.__v129){const f=function(...args){const r=native.apply(this,args);G.q('#liveContent')?.classList.add('v129-live');return r};f.__v129=true;renderLive=f;window.renderLive=f}}catch(e){console.warn('[v129 live render]',e)}
}
G.diagnostics=()=>{let iso=G.today();try{iso=selectedWorkoutDate||iso}catch(_){}const day=resolveDay(iso,''),root=rootFor(day),list=listFor(root);return{release:G.release,selectedDate:iso,plannerVisible:!!G.q('.v129-planner'),completedHidden,cardOrder:list?G.qa(':scope > .modern-exercise-card,:scope > details[data-instance-id]',list).map(x=>x.dataset.instanceId||''):[],calendarHook:typeof v124OpenCalendarDay==='function'&&!!v124OpenCalendarDay.__v129}};window.gymV129Diagnostics=G.diagnostics;
function start(){installSettings();installPlanHooks();installCalendar();installRenderHooks();let day='monday',iso=G.today();try{day=selectedTodayDay||resolveDay(selectedWorkoutDate||iso,'');iso=selectedWorkoutDate||iso}catch(_){}decorate(day,iso);if(G.q('#more')?.classList.contains('active')&&typeof renderMore==='function')renderMore()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
