/* Gym Tracker v129 detail: image first, big Play, collapsed technique + video URL */
(()=>{
'use strict';const G=window.GymV129;if(!G)return;const q=G.q,qa=G.qa,cs=G.cs,safe=G.safe;
let detailId='';
const localized=v=>{if(Array.isArray(v))return v.filter(Boolean).map(String);if(v&&typeof v==='object'){const x=v[cs()?'cs':'en']??v.en??v.cs;return Array.isArray(x)?x.filter(Boolean).map(String):(typeof x==='string'&&x.trim()?[x.trim()]:[])}return typeof v==='string'&&v.trim()?[v.trim()]:[]};
const ex=id=>{try{return EX?.[id]||null}catch(_){return null}};
function store(id){try{state.exerciseMedia=state.exerciseMedia||{};state.exerciseMedia[id]=state.exerciseMedia[id]||{files:[],links:[]};return state.exerciseMedia[id]}catch(_){return {files:[],links:[]}}}G.mediaStore=store;
function videoUrl(id){const x=ex(id),s=store(id),custom=String(s.preferredVideoUrl||'').trim();if(custom)return custom;const builtin=String(x?.videoUrl||'').trim();if(builtin)return builtin;const name=x?.en||x?.cs||id;return `https://www.youtube.com/results?search_query=${encodeURIComponent(name+' proper form tutorial')}`}G.videoUrl=videoUrl;
function detailData(id){const x=ex(id)||{},tips=localized(x.technique||x.steps||x.instructions||x.howTo||x.tips),mistakes=localized(x.commonMistakes||x.mistakes),primary=localized(x.primaryMuscles||x.primaryMuscle||x.muscles),secondary=localized(x.secondaryMuscles||x.secondaryMuscle);let group='';try{group=typeof categoryName==='function'?categoryName(x.category):String(x.category||'')}catch(_){group=String(x.category||'')}return{focus:localized(x.focusToday||x.focus||x.cue)[0]||tips[0]||'',primary:primary.length?primary:(group?[group]:[]),secondary,tips,mistakes,pro:localized(x.proTip||x.tip)[0]||''}}
function techniqueHtml(id){const d=detailData(id),rows=[];if(d.focus)rows.push(`<div><b>🎯 Focus today</b><p>${safe(d.focus)}</p></div>`);if(d.primary.length||d.secondary.length)rows.push(`<div><b>💪 ${cs()?'Svaly':'Muscles'}</b><p>${safe([d.primary.length?`${cs()?'Hlavní':'Primary'}: ${d.primary.join(', ')}`:'',d.secondary.length?`${cs()?'Vedlejší':'Secondary'}: ${d.secondary.join(', ')}`:''].filter(Boolean).join(' · '))}</p></div>`);if(d.tips.length)rows.push(`<div><b>📋 ${cs()?'Technika':'Technique'}</b><ul>${d.tips.slice(0,6).map(v=>`<li>${safe(v)}</li>`).join('')}</ul></div>`);if(d.mistakes.length)rows.push(`<div><b>⚠ ${cs()?'Časté chyby':'Common mistakes'}</b><ul>${d.mistakes.slice(0,5).map(v=>`<li>${safe(v)}</li>`).join('')}</ul></div>`);if(d.pro)rows.push(`<div><b>💡 Pro tip</b><p>${safe(d.pro)}</p></div>`);return rows.length?`<details class="v129-technique"><summary><span>ⓘ</span><strong>${cs()?'Technika & tipy':'Technique & tips'}</strong><i>›</i></summary><div class="v129-technique-body">${rows.join('')}</div></details>`:''}
function hero(id){const modal=q('#videoDialog .modal');if(!modal)return;q('.v129-video-hero',modal)?.remove();const guide=q('#videoGuideWrap',modal),title=q('#videoTitle',modal),x=ex(id),img=q('#videoGuideImage',modal);if(guide){guide.hidden=false;guide.classList.add('v129-guide-top');if(img&&(x?.guideImage||x?.guideThumb))img.src=x.guideImage||x.guideThumb;if(title&&guide.previousElementSibling!==title)title.insertAdjacentElement('afterend',guide)}const box=document.createElement('div');box.className='v129-video-hero';box.innerHTML=`<button type="button" class="v129-play-video">▶ ${cs()?'Přehrát video':'Play video'}</button>`;q('button',box)?.addEventListener('click',()=>window.open(videoUrl(id),'_blank','noopener'));(guide||title)?.insertAdjacentElement('afterend',box)}
async function savePreferred(id,raw){const value=String(raw||'').trim();if(value){try{const u=new URL(value);if(!['http:','https:'].includes(u.protocol))throw new Error()}catch(_){G.toast(cs()?'Vlož platný odkaz na video.':'Enter a valid video URL.');return}}const s=store(id);if(value){s.preferredVideoUrl=value;delete s.preferredVideoClearedAt}else{delete s.preferredVideoUrl;s.preferredVideoClearedAt=Date.now()}try{saveState()}catch(_){}try{if(typeof cloudUser!=='undefined'&&cloudUser&&typeof saveCloud==='function')await saveCloud()}catch(_){}try{if(typeof renderExerciseMedia==='function')await renderExerciseMedia(id)}catch(_){}rebuild(id);G.toast(cs()?'Video uloženo ✓':'Video saved ✓')}
async function resetPreferred(id){const s=store(id);delete s.preferredVideoUrl;s.preferredVideoClearedAt=Date.now();try{saveState()}catch(_){}try{if(typeof cloudUser!=='undefined'&&cloudUser&&typeof saveCloud==='function')await saveCloud()}catch(_){}try{if(typeof renderExerciseMedia==='function')await renderExerciseMedia(id)}catch(_){}rebuild(id);G.toast(cs()?'Obnoveno výchozí video.':'Default video restored.')}
window.v129SavePreferredVideo=savePreferred;window.v129ResetPreferredVideo=resetPreferred;
function editor(id){const panel=q('#exerciseMediaPanel');if(!panel)return;q('.v127-guide-slide',panel)?.remove();let e=q('.v127-video-editor',panel);if(!e){const s=store(id),x=ex(id),current=String(s.preferredVideoUrl||x?.videoUrl||'').trim();e=document.createElement('section');e.className='v127-video-editor';e.innerHTML=`<div class="v127-video-editor-head"><strong>Video</strong></div><div class="v127-video-editor-row"><input id="v129VideoUrl" type="url" inputmode="url" value="${safe(current)}" placeholder="https://youtube.com/…"><button type="button" class="primary v129-save-video">${cs()?'Uložit':'Save'}</button></div><div class="v127-video-editor-actions">${String(s.preferredVideoUrl||'').trim()?`<button type="button" class="v129-reset-video">↺ ${cs()?'Výchozí':'Default'}</button>`:''}</div>`;(q('.v124-media-head',panel)||panel.firstElementChild)?.insertAdjacentElement('afterend',e);q('.v129-save-video',e)?.addEventListener('click',()=>savePreferred(id,q('#v129VideoUrl',e)?.value||''));q('.v129-reset-video',e)?.addEventListener('click',()=>resetPreferred(id))}if(!e.closest('.v129-edit-video')){q('.v127-video-editor-actions .open',e)?.remove();const d=document.createElement('details');d.className='v129-edit-video';d.innerHTML=`<summary><span>⚙</span><strong>${cs()?'Upravit video':'Edit video'}</strong><i>›</i></summary>`;e.before(d);d.appendChild(e)}const linkForm=q('.v124-link-form',panel),links=q('.v124-links',panel);if(linkForm&&!linkForm.closest('.v129-extra-links')){const d=document.createElement('details');d.className='v129-extra-links';d.innerHTML=`<summary><span>🔗</span><strong>${cs()?'Další odkazy':'Extra links'}</strong><i>›</i></summary><div class="v129-extra-links-body"></div>`;linkForm.before(d);const body=q('.v129-extra-links-body',d);body.appendChild(linkForm);if(links)body.appendChild(links)}const head=q('.v124-media-head h3',panel);if(head)head.textContent=cs()?'Moje obrázky a videa':'My images & videos'}
function rebuild(id){detailId=id;requestAnimationFrame(()=>{hero(id);const tips=q('#videoTips');if(tips)tips.innerHTML=techniqueHtml(id);editor(id);q('#videoDialog .modal')?.classList.add('v129-detail-modal')})}G.rebuildDetail=rebuild;
function start(){try{const native=typeof openVideo==='function'?openVideo:null;if(native&&!native.__v129){const f=function(id,...args){const r=native.call(this,id,...args);rebuild(String(id||''));return r};f.__v129=true;openVideo=f;window.openVideo=f}}catch(e){console.warn('[v129 open video]',e)}try{const native=typeof renderExerciseMedia==='function'?renderExerciseMedia:null;if(native&&!native.__v129){const f=async function(id,...args){const r=await native.call(this,id,...args);editor(String(id||''));if(detailId===String(id||''))hero(detailId);return r};f.__v129=true;renderExerciseMedia=f;window.renderExerciseMedia=f}}catch(e){console.warn('[v129 media render]',e)}}
start();
})();
