/* Gym Tracker v129 cloud/media merge safety */
(()=>{'use strict';const G=window.GymV129;if(!G)return;const store=id=>{try{state.exerciseMedia=state.exerciseMedia||{};state.exerciseMedia[id]=state.exerciseMedia[id]||{files:[],links:[]};return state.exerciseMedia[id]}catch(_){return {files:[],links:[]}}};
function meaningful(s){if((s?.customExercises||[]).length)return true;return Object.values(s?.exerciseMedia||{}).some(x=>(x?.files||[]).length||(x?.links||[]).length||String(x?.preferredVideoUrl||'').trim())}
function mergeMedia(a={},b={},preferA=true){const out={},ids=new Set([...Object.keys(a||{}),...Object.keys(b||{})]);for(const id of ids){const first=preferA?(a?.[id]||{}):(b?.[id]||{}),second=preferA?(b?.[id]||{}):(a?.[id]||{}),clone=x=>{try{return JSON.parse(JSON.stringify(x))}catch(_){return x}};const df=[...(first.deletedFiles||[]),...(second.deletedFiles||[])],dfk=new Set(df.flatMap(x=>[x?.id,x?.path].filter(Boolean))),files=[],fk=new Set();[...(first.files||[]),...(second.files||[])].forEach(x=>{const k=x?.id||x?.path||JSON.stringify(x);if(dfk.has(x?.id)||dfk.has(x?.path)||fk.has(k))return;fk.add(k);files.push(clone(x))});const dl=[...(first.deletedLinks||[]),...(second.deletedLinks||[])],dlk=new Set(dl.flatMap(x=>[x?.id,x?.url].filter(Boolean))),links=[],lk=new Set();[...(first.links||[]),...(second.links||[])].forEach(x=>{const k=x?.id||x?.url||JSON.stringify(x);if(dlk.has(x?.id)||dlk.has(x?.url)||lk.has(k))return;lk.add(k);links.push(clone(x))});const x={files,links,deletedFiles:df.slice(-100),deletedLinks:dl.slice(-100)},c1=Number(first.preferredVideoClearedAt)||0,c2=Number(second.preferredVideoClearedAt)||0;if(c1)x.preferredVideoClearedAt=c1;else if(Object.prototype.hasOwnProperty.call(first,'preferredVideoUrl'))x.preferredVideoUrl=first.preferredVideoUrl;else if(Object.prototype.hasOwnProperty.call(second,'preferredVideoUrl')&&!c2)x.preferredVideoUrl=second.preferredVideoUrl;else if(c2)x.preferredVideoClearedAt=c2;out[id]=x}return out}G.mergeMedia=mergeMedia;
try{const native=typeof hasMeaningfulLocalData==='function'?hasMeaningfulLocalData:null;if(native&&!native.__v129){const f=function(){return native.call(this)||meaningful(state)};f.__v129=true;hasMeaningfulLocalData=f;window.hasMeaningfulLocalData=f}}catch(e){console.warn('[v129 local safety]',e)}
try{const native=typeof mergeStates==='function'?mergeStates:null;if(native&&!native.__v129){const f=function(local,remote){const merged=native.call(this,local,remote),lt=Number(local?.meta?.modifiedAt)||0,rt=Number(remote?.meta?.modifiedAt)||0;merged.exerciseMedia=mergeMedia(local?.exerciseMedia||{},remote?.exerciseMedia||{},lt>=rt);return merged};f.__v129=true;mergeStates=f;window.mergeStates=f}}catch(e){console.warn('[v129 merge safety]',e)}
try{const native=typeof v124DeleteExerciseMedia==='function'?v124DeleteExerciseMedia:null;if(native&&!native.__v129){const f=async function(exerciseId,itemId){const before=(store(exerciseId).files||[]).find(x=>x?.id===itemId),r=await native.call(this,exerciseId,itemId),s=store(exerciseId);if(before&&!s.files.some(x=>x?.id===itemId)){s.deletedFiles=[...(s.deletedFiles||[]).filter(x=>x?.id!==itemId),{id:itemId,path:before.path||'',at:Date.now()}].slice(-100);try{saveState()}catch(_){}}return r};f.__v129=true;v124DeleteExerciseMedia=f;window.v124DeleteExerciseMedia=f}}catch(e){console.warn('[v129 delete media]',e)}
try{const native=typeof v124RemoveExerciseLink==='function'?v124RemoveExerciseLink:null;if(native&&!native.__v129){const f=function(exerciseId,itemId){const before=(store(exerciseId).links||[]).find(x=>x?.id===itemId),r=native.call(this,exerciseId,itemId),s=store(exerciseId);if(before&&!s.links.some(x=>x?.id===itemId)){s.deletedLinks=[...(s.deletedLinks||[]).filter(x=>x?.id!==itemId),{id:itemId,url:before.url||'',at:Date.now()}].slice(-100);try{saveState()}catch(_){}}return r};f.__v129=true;v124RemoveExerciseLink=f;window.v124RemoveExerciseLink=f}}catch(e){console.warn('[v129 delete link]',e)}
})();
