/* Gym Tracker v130: undo completed exercise + tomorrow/custom calendar planning */
(()=>{
'use strict';
const G129=window.GymV129||{};
const V={release:'v130',CUSTOM_KEY:'gymCustomWorkoutsV130'};
const q=(s,r=document)=>r?.querySelector?.(s)||null;
const qa=(s,r=document)=>Array.from(r?.querySelectorAll?.(s)||[]);
const cs=()=>{try{return typeof lang==='function'&&lang()==='cs'}catch(_){return true}};
const todayIso=()=>{try{return typeof today==='function'?today():new Date().toISOString().slice(0,10)}catch(_){return new Date().toISOString().slice(0,10)}};
const currentIso=()=>{try{return selectedWorkoutDate||todayIso()}catch(_){return todayIso()}};
const safe=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
const toast=msg=>{try{if(typeof showToast==='function')showToast(msg)}catch(_){}};
function readCustom(){try{return JSON.parse(localStorage.getItem(V.CUSTOM_KEY)||'{}')||{}}catch(_){return {}}}
function writeCustom(v){try{localStorage.setItem(V.CUSTOM_KEY,JSON.stringify(v||{}))}catch(_){}}
function customFor(iso=currentIso()){const v=readCustom()[iso];return v&&Array.isArray(v.exerciseIds)&&v.exerciseIds.length?v:null}
function clearCustom(iso){const all=readCustom();delete all[iso];writeCustom(all)}
function allExercises(){try{if(Array.isArray(LIBRARY)&&LIBRARY.length)return LIBRARY}catch(_){}try{return Object.values(EX||{})}catch(_){return []}}
function exerciseName(x){try{return typeof itemName==='function'?itemName(x):(cs()?x.cs:x.en)||x.en||x.cs||x.id}catch(_){return x?.en||x?.cs||x?.id||''}}
function categoryText(x){try{return typeof categoryName==='function'?categoryName(x.category):String(x.category||'')}catch(_){return String(x?.category||'')}}
function installDayInstances(){try{const native=typeof dayInstances==='function'?dayInstances:null;if(!native||native.__v130)return;const f=function(day,...args){const custom=customFor();if(custom){return custom.exerciseIds.map((id,index)=>{const x=(()=>{try{return EX?.[id]}catch(_){return null}})()||allExercises().find(e=>e.id===id)||{};return {instanceId:`custom:${currentIso()}:${index}:${id}`,exerciseId:id,sets:x.sets,range:x.range,added:false};})}return native.call(this,day,...args)};f.__v130=true;f.__native=native;dayInstances=f;window.dayInstances=f}catch(e){console.warn('[v130 dayInstances]',e)}}
function undoExercise(day,id){try{const e=entry(day,id);if(!e)return;e.done=false;e.skipped=false;if(Array.isArray(e.sets))e.sets.forEach(set=>{if(set&&typeof set==='object')set._complete=false});if(state?.days?.[day])state.days[day].completed=false;saveState();renderDay(day);toast(cs()?'Cvik vrácen jako nedokončený':'Exercise marked unfinished')}catch(err){console.warn('[v130 undo]',err);toast(cs()?'Nepodařilo se vrátit cvik':'Could not undo exercise')}}
V.undoExercise=undoExercise;window.v130UndoExercise=undoExercise;
function decorateUndo(day){const root=document.getElementById(day)||q('.screen.active');if(!root)return;qa('.today-preview-list .modern-exercise-card.exercise-done',root).forEach(card=>{if(card.querySelector('.v130-undo-complete'))return;const id=card.dataset.instanceId;if(!id)return;const main=q('.preview-card-main',card)||q('summary',card);if(!main)return;const b=document.createElement('button');b.type='button';b.className='v130-undo-complete';b.textContent=cs()?'↩ Zrušit hotovo':'↩ Undo complete';b.addEventListener('click',ev=>{ev.preventDefault();ev.stopPropagation();const ok=confirm(cs()?'Označit tento cvik znovu jako nedokončený? Zadané hodnoty zůstanou uložené.':'Mark this exercise as unfinished? Entered values will be kept.');if(ok)undoExercise(day,id)});main.appendChild(b)})}
function plannerDate(root){return root?.dataset?.v129Date||currentIso()}
function ensureCustomPlanner(day,iso){const root=document.getElementById(day)||q('.screen.active');if(!root)return;const planner=q('.v129-planner',root);if(!planner)return;const date=plannerDate(planner)||iso;const custom=customFor(date);qa('[data-v129-day]',planner).forEach(btn=>{if(custom)btn.classList.remove('selected');if(btn.dataset.v130PresetBound!=='1'){btn.dataset.v130PresetBound='1';btn.addEventListener('click',()=>clearCustom(date),{capture:true})}});const clear=q('.v129-clear-plan',planner);if(clear&&clear.dataset.v130Bound!=='1'){clear.dataset.v130Bound='1';clear.addEventListener('click',()=>clearCustom(date),{capture:true})}let btn=q('.v130-custom-plan',planner);if(!btn){btn=document.createElement('button');btn.type='button';btn.className='v130-custom-plan';const grid=q('.v129-plan-grid',planner);(grid||planner).appendChild(btn);btn.addEventListener('click',()=>openCustomDialog(date))}btn.classList.toggle('selected',!!custom);btn.innerHTML=`<b>${custom?(cs()?'✓ Vlastní trénink':'✓ Custom workout'):(cs()?'＋ Vlastní trénink':'＋ Custom workout')}</b><small>${custom?`${custom.exerciseIds.length} ${cs()?'cviků':'exercises'}`:(cs()?'Vyber vlastní cviky':'Choose exercises')}</small>`;if(custom){const h=q('.v129-planner h3',planner);if(h)h.textContent=cs()?'Vlastní trénink naplánován':'Custom workout planned'}}
function ensureDialog(){let d=q('#v130CustomDialog');if(d)return d;d=document.createElement('dialog');d.id='v130CustomDialog';d.innerHTML=`<div class="modal v130-custom-modal"><button type="button" class="iconbtn close v130-custom-close">✕</button><div class="v130-custom-head"><span>${cs()?'VLASTNÍ TRÉNINK':'CUSTOM WORKOUT'}</span><h2>${cs()?'Vyber cviky':'Choose exercises'}</h2><p>${cs()?'Vyber cviky pro konkrétní den. Pořadí můžeš upravit odebráním a novým výběrem.':'Choose exercises for this date.'}</p></div><input class="v130-custom-search" type="search" placeholder="${cs()?'Hledat cvik…':'Search exercise…'}"><div class="v130-selected-count"></div><div class="v130-custom-list"></div><div class="v130-custom-actions"><button type="button" class="secondary v130-custom-cancel">${cs()?'Zrušit':'Cancel'}</button><button type="button" class="primary v130-custom-save">${cs()?'Uložit trénink':'Save workout'}</button></div></div>`;document.body.appendChild(d);q('.v130-custom-close',d).onclick=()=>d.close();q('.v130-custom-cancel',d).onclick=()=>d.close();return d}
let editingDate='';let selectedIds=[];
function renderExercisePicker(filter=''){const d=ensureDialog(),list=q('.v130-custom-list',d);if(!list)return;const needle=String(filter||'').trim().toLowerCase();const items=allExercises().filter(x=>!needle||`${x.id} ${x.cs||''} ${x.en||''} ${x.category||''}`.toLowerCase().includes(needle));list.innerHTML=items.map(x=>{const checked=selectedIds.includes(x.id);return `<label class="v130-pick ${checked?'selected':''}"><input type="checkbox" value="${safe(x.id)}" ${checked?'checked':''}><span><b>${safe(exerciseName(x))}</b><small>${safe(categoryText(x))}</small></span></label>`}).join('')||`<div class="empty">${cs()?'Žádný cvik nenalezen':'No exercise found'}</div>`;qa('input[type=checkbox]',list).forEach(input=>input.addEventListener('change',()=>{const id=input.value;if(input.checked){if(!selectedIds.includes(id))selectedIds.push(id)}else selectedIds=selectedIds.filter(x=>x!==id);input.closest('.v130-pick')?.classList.toggle('selected',input.checked);updateCount()}));updateCount()}
function updateCount(){const d=ensureDialog(),box=q('.v130-selected-count',d);if(box)box.textContent=`${selectedIds.length} ${cs()?'vybraných cviků':'exercises selected'}`}
function openCustomDialog(iso){editingDate=iso;selectedIds=[...(customFor(iso)?.exerciseIds||[])];const d=ensureDialog();const search=q('.v130-custom-search',d);search.value='';search.oninput=()=>renderExercisePicker(search.value);q('.v130-custom-save',d).onclick=saveCustomWorkout;renderExercisePicker();d.showModal()}
function saveCustomWorkout(){if(!editingDate)return;if(!selectedIds.length){toast(cs()?'Vyber alespoň jeden cvik':'Choose at least one exercise');return}const all=readCustom();all[editingDate]={exerciseIds:[...selectedIds],updatedAt:Date.now()};writeCustom(all);try{const plans=G129.readPlans?G129.readPlans():JSON.parse(localStorage.getItem('gymPlannedWorkoutsV126')||'{}');plans[editingDate]='monday';if(G129.writePlans)G129.writePlans(plans);else localStorage.setItem('gymPlannedWorkoutsV126',JSON.stringify(plans))}catch(_){}ensureDialog().close();try{if(G129.setDate)G129.setDate(editingDate);else selectedWorkoutDate=editingDate}catch(_){}try{showToday('monday',editingDate)}catch(_){try{renderDay('monday')}catch(__){}}toast(cs()?'Vlastní trénink uložen ✓':'Custom workout saved ✓')}
V.openCustomDialog=openCustomDialog;window.v130OpenCustomWorkout=openCustomDialog;
function decorateCustomHero(day){const custom=customFor();if(!custom)return;const root=document.getElementById(day)||q('.screen.active');if(!root)return;const title=q('.workout-hero h2',root);if(title)title.textContent=cs()?'Vlastní trénink':'Custom workout';const sub=q('.workout-hero p',root);if(sub)sub.textContent=cs()?`${custom.exerciseIds.length} vybraných cviků pro tento den`:`${custom.exerciseIds.length} selected exercises for this date`}
function decorate(day,iso=currentIso()){requestAnimationFrame(()=>{decorateUndo(day);ensureCustomPlanner(day,iso);decorateCustomHero(day)})}
function installHooks(){try{const native=typeof renderDay==='function'?renderDay:null;if(native&&!native.__v130){const f=function(day,...args){const r=native.call(this,day,...args);decorate(day,currentIso());return r};f.__v130=true;renderDay=f;window.renderDay=f}}catch(e){console.warn('[v130 renderDay]',e)}try{const native=typeof refreshTodayPreviewStatus==='function'?refreshTodayPreviewStatus:null;if(native&&!native.__v130){const f=function(day,id,...args){const r=native.call(this,day,id,...args);decorateUndo(day);return r};f.__v130=true;refreshTodayPreviewStatus=f;window.refreshTodayPreviewStatus=f}}catch(e){console.warn('[v130 status]',e)}try{const native=typeof v124OpenCalendarDay==='function'?v124OpenCalendarDay:null;if(native&&!native.__v130){const f=function(iso,...args){const date=String(iso||'');if(!date)return;const r=native.call(this,date,...args);if(date>todayIso())setTimeout(()=>{let day='monday';try{day=G129.resolveDay?G129.resolveDay(date,''):day}catch(_){}ensureCustomPlanner(day,date)},0);return r};f.__v130=true;v124OpenCalendarDay=f;window.v124OpenCalendarDay=f}}catch(e){console.warn('[v130 calendar]',e)}}
V.diagnostics=()=>({release:V.release,date:currentIso(),tomorrowAllowed:(()=>{const d=new Date(todayIso()+'T12:00:00');d.setDate(d.getDate()+1);return d.toISOString().slice(0,10)>todayIso()})(),custom:customFor(),undoButtons:qa('.v130-undo-complete').length});window.GymV130=V;window.gymV130Diagnostics=V.diagnostics;
function start(){installDayInstances();installHooks();let day='monday';try{day=selectedTodayDay||G129.resolveDay?.(currentIso(),'')||day}catch(_){}decorate(day,currentIso())}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
