/* Gym Tracker v136: coach suggestions, machine setup and training progress */
(()=>{
'use strict';
const V={release:'v136'};
const q=(s,r=document)=>r?.querySelector?.(s)||null;
const qa=(s,r=document)=>Array.from(r?.querySelectorAll?.(s)||[]);
const cs=()=>{try{return typeof lang==='function'&&lang()==='cs'}catch(_){return true}};
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const ex=id=>{try{return EX?.[id]||null}catch(_){return null}};
const nameFor=id=>{const x=ex(id);try{return x&&typeof itemName==='function'?itemName(x):(x?.[cs()?'cs':'en']||x?.en||x?.cs||id)}catch(_){return x?.en||x?.cs||id}};
function ensureState(){try{state.machineSetups=state.machineSetups||{};state.aiCoachCache=state.aiCoachCache||{}}catch(_){}}
function records(id){try{return Array.isArray(state?.history?.[id])?state.history[id]:[]}catch(_){return []}}
function dataSets(rec){return (rec?.sets||[]).filter(s=>s&&typeof s==='object'&&Object.values(s).some(v=>v!==''&&v!==null&&v!==undefined&&v!==false))}
function targetRange(x){const vals=String(x?.range||'').match(/\d+(?:\.\d+)?/g)?.map(Number)||[];if(vals.length>=2)return{low:Math.min(vals[0],vals[1]),high:Math.max(vals[0],vals[1])};if(vals.length===1)return{low:vals[0],high:vals[0]};return{low:8,high:12}}
function lastSummary(id){const a=records(id),r=a.at(-1);if(!r)return'';try{return typeof formatRecord==='function'?formatRecord(r):''}catch(_){return''}}
function localCoach(id){
 const x=ex(id),a=records(id),last=a.at(-1);
 if(!x||!last)return{kind:'learn',title:cs()?'Ještě sbírám data':'Still learning',text:cs()?'Po prvním uloženém výkonu ti doporučení naváže na předchozí trénink.':'After your first saved performance, the recommendation will use your previous workout.'};
 const sets=dataSets(last);
 if(x.mode==='weight'&&sets.length){
  const weights=sets.map(s=>num(s.kg)).filter(v=>v!==null),reps=sets.map(s=>num(s.reps)).filter(v=>v!==null);
  if(!weights.length||!reps.length)return{kind:'hold',title:cs()?'Opakuj poslední výkon':'Repeat the last performance',text:lastSummary(id)};
  const weight=weights.at(-1),range=targetRange(x),step=(()=>{try{return typeof exerciseStep==='function'?Number(exerciseStep(id))||2.5:2.5}catch(_){return 2.5}})();
  const allHigh=reps.length>=Math.min(2,sets.length)&&reps.every(r=>r>=range.high),anyLow=reps.some(r=>r<range.low),prev=a.at(-2),prevSets=dataSets(prev),prevReps=prevSets.map(s=>num(s.reps)).filter(v=>v!==null),prevWeights=prevSets.map(s=>num(s.kg)).filter(v=>v!==null),twiceHigh=allHigh&&prevReps.length>0&&prevReps.every(r=>r>=range.high)&&prevWeights.length>0&&Math.abs((prevWeights.at(-1)||0)-weight)<0.001;
  if(twiceHigh){const next=Math.round((weight+step)*10)/10;return{kind:'consider',title:cs()?'Můžeš zvážit malý krok':'Consider a small step',text:cs()?`Poslední dva tréninky byly na horní hranici cíle. Pokud je technika stále jistá, zvaž ${next} kg; jinak klidně zopakuj ${weight} kg.`:`The last two sessions reached the top of the target range. If technique still feels controlled, consider ${next} kg; otherwise repeat ${weight} kg.`}}
  if(anyLow)return{kind:'hold',title:cs()?'Zatím nepřidávej':'Hold the load for now',text:cs()?`Zopakuj přibližně ${weight} kg a soustřeď se na čisté opakování v cílovém rozsahu.`:`Repeat about ${weight} kg and focus on controlled reps in the target range.`};
  return{kind:'hold',title:cs()?'Navázat na minule':'Build on the last session',text:cs()?`Začni kolem ${weight} kg a zkus navázat na poslední počet opakování. Přidávej jen pokud je technika stabilní.`:`Start around ${weight} kg and build from the previous reps. Only progress if technique stays controlled.`};
 }
 if(x.mode==='reps'&&sets.length){const reps=sets.map(s=>num(s.reps)).filter(v=>v!==null),lastRep=reps.at(-1);return{kind:'hold',title:cs()?'Navázat na minule':'Build on the last session',text:lastRep!==undefined?(cs()?`Začni kolem ${lastRep} opakování a uprav podle toho, jak se série cítí.`:`Start around ${lastRep} reps and adjust based on how the set feels.`):lastSummary(id)}}
 if(x.mode==='time'&&sets.length){const secs=sets.map(s=>num(s.seconds)).filter(v=>v!==null),lastSec=secs.at(-1);return{kind:'hold',title:cs()?'Navázat na minule':'Build on the last session',text:lastSec!==undefined?(cs()?`Začni kolem ${lastSec} s. Čas navyšuj jen pokud držíš dobrou pozici.`:`Start around ${lastSec}s. Only extend time if position stays controlled.`):lastSummary(id)}}
 return{kind:'hold',title:cs()?'Poslední výkon':'Previous performance',text:lastSummary(id)||(cs()?'Použij poslední uložené hodnoty jako výchozí bod.':'Use the last saved values as a starting point.')};
}
V.localCoach=localCoach;
function setupFor(id){ensureState();try{return state.machineSetups[id]||{}}catch(_){return{}}}
function setupSummary(id){const s=setupFor(id),parts=[];if(s.seat)parts.push(`${cs()?'Sedadlo':'Seat'} ${s.seat}`);if(s.backrest)parts.push(`${cs()?'Opěra':'Back'} ${s.backrest}`);if(s.pad)parts.push(`${cs()?'Podložka':'Pad'} ${s.pad}`);if(s.pin)parts.push(`${cs()?'Pin':'Pin'} ${s.pin}`);return parts.join(' · ')||(s.note?String(s.note).slice(0,70):'')}
function ensureSetupDialog(){let d=q('#v136SetupDialog');if(d)return d;d=document.createElement('dialog');d.id='v136SetupDialog';d.className='v136-setup-dialog';d.innerHTML=`<div class="v136-setup-shell"><div class="v136-setup-head"><div><span>⚙</span><div><small>${cs()?'NASTAVENÍ STROJE':'MACHINE SETUP'}</small><h3 id="v136SetupTitle"></h3></div></div><button type="button" id="v136SetupClose">✕</button></div><div id="v136SetupBody"></div></div>`;document.body.appendChild(d);q('#v136SetupClose',d)?.addEventListener('click',()=>d.close());return d}
let setupExerciseId='';
function openMachineSetup(id){ensureState();setupExerciseId=String(id||'');const x=ex(setupExerciseId);if(!x)return;const d=ensureSetupDialog(),s=setupFor(setupExerciseId);q('#v136SetupTitle',d).textContent=nameFor(setupExerciseId);q('#v136SetupBody',d).innerHTML=`<div class="v136-setup-grid"><label><span>${cs()?'Sedadlo':'Seat'}</span><input id="v136Seat" value="${safe(s.seat||'')}" placeholder="${cs()?'např. 4':'e.g. 4'}"></label><label><span>${cs()?'Opěradlo':'Backrest'}</span><input id="v136Backrest" value="${safe(s.backrest||'')}" placeholder="${cs()?'např. 2':'e.g. 2'}"></label><label><span>${cs()?'Podložka / rameno':'Pad / arm'}</span><input id="v136Pad" value="${safe(s.pad||'')}" placeholder="${cs()?'např. 3':'e.g. 3'}"></label><label><span>${cs()?'Pin / další nastavení':'Pin / other setting'}</span><input id="v136Pin" value="${safe(s.pin||'')}" placeholder="${cs()?'např. B':'e.g. B'}"></label></div><label class="v136-note"><span>${cs()?'Poznámka':'Note'}</span><textarea id="v136SetupNote" rows="3" placeholder="${cs()?'Co si chceš pamatovat příště…':'What you want to remember next time…'}">${safe(s.note||'')}</textarea></label><p class="v136-setup-photo-note">📷 ${cs()?'Fotku stroje můžeš uložit v „Moje obrázky a videa“ u tohoto cviku.':'You can save a machine photo in “My images & videos” for this exercise.'}</p><button type="button" class="primary full" id="v136SetupSave">${cs()?'Uložit nastavení':'Save setup'}</button>`;q('#v136SetupSave',d)?.addEventListener('click',saveMachineSetup);if(!d.open)d.showModal()}
window.openMachineSetup=openMachineSetup;
function saveMachineSetup(){if(!setupExerciseId)return;ensureState();const val=id=>String(q(id)?.value||'').trim(),s={seat:val('#v136Seat'),backrest:val('#v136Backrest'),pad:val('#v136Pad'),pin:val('#v136Pin'),note:val('#v136SetupNote'),updatedAt:Date.now()};state.machineSetups[setupExerciseId]=s;try{saveState()}catch(_){}try{if(typeof cloudUser!=='undefined'&&cloudUser&&typeof saveCloud==='function')saveCloud()}catch(_){}q('#v136SetupDialog')?.close();decorateLive();decorateDetail(setupExerciseId);try{if(typeof showToast==='function')showToast(cs()?'Nastavení stroje uloženo ✓':'Machine setup saved ✓')}catch(_){}}
function coachCard(id){const rec=localCoach(id);return`<div class="v136-coach-card ${rec.kind}"><div class="v136-coach-copy"><small>✦ ${cs()?'COACH DOPORUČENÍ':'COACH SUGGESTION'}</small><strong>${safe(rec.title)}</strong><p>${safe(rec.text)}</p></div><button type="button" onclick="GymV136.askAI('${safe(id)}')">AI</button></div>`}
function decorateLive(){try{if(!state?.activeWorkout)return;const inst=currentLive?.();if(!inst)return;const day=state.activeWorkout.day,m=metaFor(day,inst),root=q('#liveContent')||document;qa('.v136-live-tools,.v136-coach-card',root).forEach(x=>x.remove());const anchor=q('.live-round-metrics',root)||q('.modern-live-set',root)||q('.saved-sets-panel',root);if(!anchor)return;const tools=document.createElement('div');tools.className='v136-live-tools';const summary=setupSummary(m.id);tools.innerHTML=`<button type="button" onclick="openMachineSetup('${safe(m.id)}')">⚙ <span>${cs()?'Nastavení stroje':'Machine setup'}</span>${summary?`<small>${safe(summary)}</small>`:''}</button>`;anchor.before(tools);const c=document.createElement('div');c.innerHTML=coachCard(m.id);anchor.before(c.firstElementChild)}catch(e){console.warn('[v136 live]',e)}}
function decorateDetail(id){const modal=q('#videoDialog .modal');if(!modal||!id)return;q('.v136-detail-setup',modal)?.remove();const box=document.createElement('details');box.className='v136-detail-setup';const summary=setupSummary(id);box.innerHTML=`<summary><span>⚙</span><strong>${cs()?'Nastavení stroje':'Machine setup'}</strong><i>›</i></summary><div class="v136-detail-setup-body">${summary?`<p>${safe(summary)}</p>`:`<p>${cs()?'Zatím bez uloženého nastavení.':'No saved setup yet.'}</p>`}<button type="button" class="secondary full">${cs()?'Upravit nastavení':'Edit setup'}</button></div>`;q('button',box)?.addEventListener('click',()=>openMachineSetup(id));const hero=q('.v129-video-hero',modal)||q('#videoGuideWrap',modal)||q('#videoTitle',modal);hero?.insertAdjacentElement('afterend',box)}
function scoreRecord(rec){const sets=dataSets(rec);if(rec?.mode==='weight')return sets.reduce((a,s)=>a+(num(s.kg)||0)*(num(s.reps)||0),0);if(rec?.mode==='reps')return sets.reduce((a,s)=>a+(num(s.reps)||0),0);if(rec?.mode==='time')return sets.reduce((a,s)=>a+(num(s.seconds)||0),0);if(rec?.mode==='sideweight')return sets.reduce((a,s)=>a+(num(s.kg)||0)*((num(s.left)||0)+(num(s.right)||0)),0);if(rec?.mode==='sidetime')return sets.reduce((a,s)=>a+(num(s.leftSeconds)||0)+(num(s.rightSeconds)||0),0);return 0}
function trainingProgressMarkup(){const histories=Object.entries(state?.history||{}).filter(([,a])=>Array.isArray(a)&&a.length),strength=(state?.workouts||[]).filter(w=>w?.type!=='cardio'),cutoff=Date.now()-30*86400000,recent=strength.filter(w=>{const d=Date.parse(`${w.date||''}T00:00:00`);return Number.isFinite(d)&&d>=cutoff}),rows=histories.map(([id,a])=>{const last=a.at(-1),prev=a.at(-2),ls=scoreRecord(last),ps=scoreRecord(prev),trend=prev?(ls>ps*1.03?'↑':ls<ps*.97?'↓':'→'):'·';return{id,last,trend,date:last?.date||''}}).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6);return`<section class="v136-progress-card"><div class="v136-progress-head"><div><small>${cs()?'TRÉNINK':'TRAINING'}</small><h3>${cs()?'Progres ve cvičení':'Training progress'}</h3></div></div><div class="v136-progress-stats"><div><strong>${recent.length}</strong><span>${cs()?'silových tréninků / 30 dní':'strength workouts / 30 days'}</span></div><div><strong>${histories.length}</strong><span>${cs()?'cviků s historií':'exercises tracked'}</span></div></div><div class="v136-progress-list">${rows.length?rows.map(r=>`<button type="button" onclick="openHistory('${safe(r.id)}')"><span><strong>${safe(nameFor(r.id))}</strong><small>${safe(r.date)} · ${safe(lastSummary(r.id))}</small></span><b class="${r.trend==='↑'?'up':r.trend==='↓'?'down':''}">${r.trend}</b></button>`).join(''):`<p class="v136-empty">${cs()?'Až uložíš tréninky, tady uvidíš vývoj jednotlivých cviků.':'Save workouts to see exercise trends here.'}</p>`}</div></section>`}
function decorateProgress(){const root=q('#progress');if(!root)return;q('.v136-progress-card',root)?.remove();const first=root.firstElementChild;if(!first)return;const wrap=document.createElement('div');wrap.innerHTML=trainingProgressMarkup();first.before(wrap.firstElementChild)}
function mergeSetupMaps(a={},b={}){const out={};for(const[id,s]of Object.entries(a||{}))out[id]={...s};for(const[id,s]of Object.entries(b||{})){const old=out[id];if(!old||Number(s?.updatedAt||0)>=Number(old?.updatedAt||0))out[id]={...s}}return out}
function installMerge(){try{const native=typeof mergeStates==='function'?mergeStates:null;if(!native||native.__v136)return;const f=function(local,remote){const m=native.call(this,local,remote);m.machineSetups=mergeSetupMaps(local?.machineSetups,remote?.machineSetups);m.aiCoachCache=mergeSetupMaps(local?.aiCoachCache,remote?.aiCoachCache);return m};f.__v136=true;f.__native=native;mergeStates=f;window.mergeStates=f}catch(e){console.warn('[v136 merge]',e)}}
function installHooks(){const wrap=(name,after)=>{try{const native=window[name]||eval(`typeof ${name}==='function'?${name}:null`);if(typeof native!=='function'||native.__v136)return;const f=function(...args){const r=native.apply(this,args);Promise.resolve(r).finally(()=>requestAnimationFrame(()=>after(...args)));return r};f.__v136=true;f.__native=native;try{eval(`${name}=f`)}catch(_){}window[name]=f}catch(_){}};wrap('renderLive',decorateLive);wrap('openVideo',id=>decorateDetail(String(id||'')));wrap('renderProgress',decorateProgress)}
function aiContext(id){const x=ex(id),a=records(id).slice(-3);return{exercise:{id,name:nameFor(id),mode:x?.mode||'',target:x?.range||'',sets:x?.sets||0},history:a.map(r=>({date:r.date,mode:r.mode,sets:dataSets(r).map(s=>({kg:s.kg||'',reps:s.reps||'',seconds:s.seconds||'',left:s.left||'',right:s.right||'',leftSeconds:s.leftSeconds||'',rightSeconds:s.rightSeconds||''}))}))}}
async function askAI(id){const local=localCoach(id);let text='',source='local';try{if(typeof cloudUser!=='undefined'&&cloudUser&&typeof supabaseClient!=='undefined'&&supabaseClient?.functions?.invoke){const{data,error}=await supabaseClient.functions.invoke('ai-coach',{body:aiContext(id)});if(!error&&data?.suggestion){text=String(data.suggestion);source='ai'}}}catch(e){console.warn('[v136 ai]',e)}if(!text)text=`${local.title}. ${local.text}`;ensureState();state.aiCoachCache[id]={text,source,updatedAt:Date.now()};try{saveState(false)}catch(_){}const card=q('.v136-coach-card');if(card){q('.v136-coach-copy strong',card).textContent=source==='ai'?(cs()?'AI Coach':'AI Coach'):local.title;q('.v136-coach-copy p',card).textContent=text;card.classList.toggle('ai',source==='ai')}try{if(typeof showToast==='function')showToast(source==='ai'?(cs()?'AI doporučení aktualizováno ✓':'AI suggestion updated ✓'):(cs()?'Použito bezpečné lokální doporučení.':'Using the safe local recommendation.'))}catch(_){}}
V.askAI=askAI;window.GymV136=V;V.diagnostics=()=>({release:V.release,machineSetups:Object.keys(state?.machineSetups||{}).length,aiReady:!!(()=>{try{return cloudUser&&supabaseClient?.functions?.invoke}catch(_){return false}})(),coachForCurrent:(()=>{try{const i=currentLive?.();return i?localCoach(metaFor(state.activeWorkout.day,i).id):null}catch(_){return null}})()});window.gymV136Diagnostics=V.diagnostics;
function start(){ensureState();installMerge();installHooks();requestAnimationFrame(()=>{decorateLive();decorateProgress()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();