/* Gym Tracker v138: deterministic session rotation + cloud/local parity */
(()=>{
'use strict';
const V={release:'v138'},DAYS=['monday','wednesday','friday'];
const LEGACY_MANUAL='gymManualSessionByDateV137';
const LEGACY_PLAN=window.GymV129?.PLAN_KEY||'gymPlannedWorkoutsV126';
const todayIso=()=>{try{return typeof today==='function'?today():new Date().toISOString().slice(0,10)}catch(_){return new Date().toISOString().slice(0,10)}};
const currentIso=()=>{try{return String(selectedWorkoutDate||todayIso())}catch(_){return todayIso()}};
const valid=d=>DAYS.includes(d);
const clone=v=>JSON.parse(JSON.stringify(v||{}));
function ensureState(target=state){if(!target)return target;target.sessionOverrides=target.sessionOverrides||{};target.calendarSessionPlans=target.calendarSessionPlans||{};return target}
function importLegacy(){ensureState();try{const old=JSON.parse(localStorage.getItem(LEGACY_MANUAL)||'{}')||{};Object.entries(old).forEach(([date,day])=>{if(valid(day)&&!state.sessionOverrides[date])state.sessionOverrides[date]={day,updatedAt:Date.now()}})}catch(_){}try{const old=JSON.parse(localStorage.getItem(LEGACY_PLAN)||'{}')||{};Object.entries(old).forEach(([date,day])=>{if(valid(day)&&!state.calendarSessionPlans[date])state.calendarSessionPlans[date]={day,updatedAt:Date.now()}})}catch(_){}}
function wt(w){const s=Number(w?.savedAt)||0;if(s)return s;const d=Date.parse(`${w?.date||''}T23:59:59`);return Number.isFinite(d)?d:0}
function completed(source=state){try{return (source?.workouts||[]).filter(w=>w&&w.type!=='cardio'&&valid(w.day)).slice().sort((a,b)=>wt(a)-wt(b))}catch(_){return []}}
function next(day){const i=DAYS.indexOf(day);return i<0?'monday':DAYS[(i+1)%3]}
function auto(source=state){const last=completed(source).at(-1);return last?next(last.day):'monday'}
function overrideFor(date,source=state){ensureState(source);const v=source?.sessionOverrides?.[date];const day=typeof v==='string'?v:v?.day;return valid(day)?day:''}
function planFor(date,source=state){ensureState(source);const v=source?.calendarSessionPlans?.[date];const day=typeof v==='string'?v:v?.day;return valid(day)?day:''}
function resolve(date=currentIso(),source=state){const iso=String(date||currentIso());try{const a=source?.activeWorkout,ad=a?.date||source?.days?.[a?.day]?.date||'';if(a&&valid(a.day)&&(!ad||ad===iso))return a.day}catch(_){}const manual=overrideFor(iso,source);if(manual)return manual;if(iso<todayIso()){const done=completed(source).filter(w=>w.date===iso).at(-1);if(done)return done.day;return auto(source)}if(iso>todayIso()){const plan=planFor(iso,source);if(plan)return plan}return auto(source)}
function mergeMap(a={},b={}){const out={};for(const[k,v]of Object.entries(a||{}))out[k]=typeof v==='string'?{day:v,updatedAt:0}:clone(v);for(const[k,v0]of Object.entries(b||{})){const v=typeof v0==='string'?{day:v0,updatedAt:0}:clone(v0),old=out[k];if(!old||Number(v?.updatedAt||0)>=Number(old?.updatedAt||0))out[k]=v}return out}
function installCloudMerge(){try{const native=typeof mergeStates==='function'?mergeStates:null;if(!native||native.__v138)return;const f=function(localValue,remoteValue){const merged=native.call(this,localValue,remoteValue);ensureState(merged);merged.sessionOverrides=mergeMap(localValue?.sessionOverrides,remoteValue?.sessionOverrides);merged.calendarSessionPlans=mergeMap(localValue?.calendarSessionPlans,remoteValue?.calendarSessionPlans);return merged};f.__v138=true;f.__native=native;mergeStates=f;window.mergeStates=f}catch(e){console.warn('[v138 merge]',e)}}
function installPlanBridge(){const G=window.GymV129;if(!G)return;G.readPlans=()=>{ensureState();const out={};Object.entries(state.calendarSessionPlans||{}).forEach(([date,v])=>{const day=typeof v==='string'?v:v?.day;if(valid(day))out[date]=day});return out};G.writePlans=value=>{ensureState();const incoming=value||{},now=Date.now(),next={};Object.entries(incoming).forEach(([date,day])=>{if(valid(day)){const old=state.calendarSessionPlans[date];next[date]={day,updatedAt:(typeof old==='object'&&old?.day===day)?Number(old.updatedAt||now):now}}});state.calendarSessionPlans=next;try{localStorage.setItem(LEGACY_PLAN,JSON.stringify(incoming))}catch(_){}try{saveState()}catch(_){}}}
function installV137Bridge(){const G=window.GymV137;if(!G)return;G.automaticNextDay=()=>auto(state);G.resolvedDayForDate=iso=>resolve(iso,state);G.setManualSession=(iso,day)=>setManual(iso,day)}
let baseShow=null;
function installShowToday(){try{baseShow=typeof showToday==='function'?showToday:null;if(!baseShow||baseShow.__v138)return;const f=function(day,date,...args){const iso=String(date||currentIso());return baseShow.call(this,resolve(iso,state),iso,...args)};f.__v138=true;f.__native=baseShow;showToday=f;window.showToday=f}catch(e){console.warn('[v138 showToday]',e)}try{const native=typeof currentProgramDay==='function'?currentProgramDay:null;const f=function(){return resolve(currentIso(),state)};f.__v138=true;f.__native=native;currentProgramDay=f;window.currentProgramDay=f}catch(e){console.warn('[v138 currentProgramDay]',e)}}
function setManual(iso,day){const date=String(iso||currentIso());ensureState();if(valid(day))state.sessionOverrides[date]={day,updatedAt:Date.now()};else delete state.sessionOverrides[date];try{const legacy=JSON.parse(localStorage.getItem(LEGACY_MANUAL)||'{}')||{};if(valid(day))legacy[date]=day;else delete legacy[date];localStorage.setItem(LEGACY_MANUAL,JSON.stringify(legacy))}catch(_){}try{saveState()}catch(_){}try{document.querySelector('#v137SessionDialog')?.close()}catch(_){}const target=resolve(date,state);try{selectedWorkoutDate=date;calendarViewDate=date;localStorage.setItem('gymSelectedWorkoutDate',date)}catch(_){}if(baseShow)baseShow(target,date);else try{showToday(target,date)}catch(_){}try{if(typeof showToast==='function')showToast(valid(day)?(typeof lang==='function'&&lang()==='cs'?`Session změněna na ${day==='monday'?'Strength':day==='wednesday'?'Stability':'Control'} ✓`:'Session changed ✓'):(typeof lang==='function'&&lang()==='cs'?'Automatické pořadí obnoveno ✓':'Automatic rotation restored ✓'))}catch(_){}}
function syncV137UI(){const G=window.GymV137;if(!G)return;try{const old=G.diagnostics;G.diagnostics=()=>({...(typeof old==='function'?old():{}),release:'v138',automaticNext:auto(state),resolved:resolve(currentIso(),state),manual:overrideFor(currentIso(),state),planned:currentIso()>todayIso()?planFor(currentIso(),state):'',paritySource:'state'});window.gymV137Diagnostics=G.diagnostics}catch(_){}}
V.auto=auto;V.resolve=resolve;V.setManual=setManual;V.planFor=planFor;V.overrideFor=overrideFor;V.diagnostics=()=>({release:V.release,date:currentIso(),today:todayIso(),automaticNext:auto(state),resolved:resolve(currentIso(),state),manual:overrideFor(currentIso(),state),futurePlan:currentIso()>todayIso()?planFor(currentIso(),state):'',lastCompleted:completed(state).at(-1)||null,cloudBacked:true});window.GymV138=V;window.gymV138Diagnostics=V.diagnostics;
function start(){ensureState();importLegacy();installCloudMerge();installPlanBridge();installV137Bridge();installShowToday();syncV137UI();try{saveState(false)}catch(_){}const iso=currentIso(),target=resolve(iso,state);try{if(!state?.activeWorkout&&baseShow)baseShow(target,iso)}catch(_){}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
